import type { Metadata } from 'next';
import { poppins, satoshi } from '@/lib/fonts';
import './globals.css';
import Footer from './_components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${satoshi.variable}`}>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
